version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    platform: linux/amd64
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5

  producer:
    build: ./producer
    container_name: producer
    depends_on:
      - rabbitmq
    ports:
      - "3000:3000"

  consumer:
    build: ./consumer
    container_name: consumer
    depends_on:
      rabbitmq:
        condition: service_healthy
